### ISSUE TITLE
Release/Public Maven Repo

### ISSUE THREAD

**Issue by mreines** [jameskennard/mockito-collections#5]
There should be a release/version. 

First, thanks to Mr Kennard for this nice addition to Mockito. I think it would be helpful to designate a version for release with an eye towards publishing to a maven repository. I think maybe the Mockito project folks might be interested as well as this would be nice to roll into the core functionality of Mockito (basically wrapping .initCollections into initMocks())

**Comment by jameskennard** [comment]
It's on my list of things to do. I am intending on getting this into a public Maven repo.

**Comment by mattreines** [comment]
Any further action on this? At our company, it was difficult to get this approved - and contingent upon pushing into a public maven repo. Is there anything I can do to help you in this effort?

**Comment by jameskennard** [comment]
I have somewhere to put it (https://issues.sonatype.org/browse/OSSRH-6366), just a matter of actually publishing it. I'll shout if you can help.

**Comment by jameskennard** [comment]
There is now a first release 1.0.0-RC-01
